a= input("enter number 1:") 
b= input("enter number 2:")

print(a, "+", b ,"is", a+b)
print(a, "+", b ,"is", a+b)
print(a, "-", b ,"is", a-b)
print(a, "-", b ,"is", a-b)
print(a, "*", b ,"is", a*b)
print(a, "*", b ,"is", a*b)
print(a, "/", b ,"is", a/b)
print(a, "/", b ,"is", a/b)
print(a, "//", b ,"is", a//b)
print(a, "//", b ,"is", a//b)
print(a, "**", b ,"is", a**b)
print(a, "**", b ,"is", a**b)
print(a, "%", b ,"is", a%b)
print(a, "%", b ,"is", a%b)